### ISSUE TITLE
Obtain certificates by flotta-dev-cli

### ISSUE THREAD

**Issue by masayag** [project-flotta/flotta-dev-cli#55]
Instead of relying on the existence of certificates files under /tmp (generated by running `make get-certs` from flotta-operator project), flotta-dev-cli is capable to get the certificates (which their known names) from the k8s cluster under flotta namespace.

```
→ bin/flotta add device -n edge1
Register failed: cannot copy certificates to device: stat /tmp/ca.pem: no such file or directory
```

**Comment by arielireni** [comment]
PR #84 fixed this issue
